name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          ### Alpine 3.12
          - image: 'alpine/3.12/7.3/Dockerfile'
            os: [ARM64]
            tags: [ 'spryker/php:7.3',]
            platforms: [ "linux/arm64" ]
          - image: 'alpine/3.12/7.3/Dockerfile'
            os: [ ubuntu-latest ]
            tags: [ 'spryker/php:7.3' ]
            platforms: [ "linux/amd64" ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
