name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'alpine/3.12/7.3/Dockerfile'
            tar-name: 'zyuzka-php-7-3-arm'
            os: ARM64
            tags: [ 'spryker/php:7.3',]
            platforms: [ "linux/arm64" ]
          - image: 'alpine/3.12/7.3/Dockerfile'
            tar-name: 'zyuzka-php-7-3-amd'
            os: ubuntu-latest
            tags: [ 'spryker/php:7.3' ]
            platforms: [ "linux/amd64" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
          outputs: type=docker,dest=/tmp/${{matrix.tar-name}}.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.tar-name}}
          path: /tmp/${{matrix.tar-name}}.tar
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: zyuzka-php-7-3-amd
          path: /tmp
      - name: Download artifact2
        uses: actions/download-artifact@v3
        with:
          name: zyuzka-php-7-3-arm
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/zyuzka-php-7-3-arm.tar
          docker load --input /tmp/zyuzka-php-7-3-amd.tar
          docker image ls -a

#          docker manifest create \
#          your-username/multiarch-example:manifest-latest \
#          --amend your-username/multiarch-example:manifest-amd64 \
#          --amend your-username/multiarch-example:manifest-arm32v7 \
#          --amend your-username/multiarch-example:manifest-arm64v8