name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          ## Alpine
          ### Alpine 3.12
          - image: 'alpine/3.12/7.3/Dockerfile'
            os: [ARM64]
            tags: [ 'spryker/php:latest', 'spryker/php:7.3', 'spryker/php:7.3-alpine3.12' ]
            platform: [ "linux/amd64", "linux/arm64" ]

    steps:
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.plaforms) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
