name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'alpine/3.12/7.3/Dockerfile'
            tar-name: 'zyuzka-php-7-3-arm'
            os: ARM64
            tags: [ 'zyuzka/php:7.3-arm']
            platforms: [ "linux/arm64" ]

          - image: 'alpine/3.12/7.3/Dockerfile'
            tar-name: 'zyuzka-php-7-3-amd'
            os: ubuntu-latest
            tags: [ 'zyuzka/php:7.3-amd' ]
            platforms: [ "linux/amd64" ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load Docker image
        run: |
          docker pull zyuzka/php:7.3-amd
          docker pull zyuzka/php:7.3-arm
          
          docker images ls
          
          docker manifest create \
            zyuzka/php:7.3-merge \
            --amend zyuzka/php:7.3-amd \
            --amend zyuzka/php:7.3-arm
          
          docker manifest push zyuzka/php:7.3-merge