name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORGA: 'zyuzka'
    strategy:
      matrix:
        include:
          # Alpine
          - image: 'alpine/3.12/7.3/Dockerfile'
            tag: "$ORGA/php:latest,$ORGA/php:7.3,$ORGA/php:7.4-alpine3.12"

#          - image: 'alpine/3.12/7.3/Dockerfile'
#            tag: "$ORGA/php:7.3"
#            tag: ["$ORGA/php:latest", "$ORGA/php:7.3", "$ORGA/php:7.4-alpine3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Install platform emulator collection
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build the image
        run: docker buildx build --push . --file ${{ matrix.image }} --tag ${{ matrix.tag }} --platform linux/amd64,linux/arm64


#docker buildx build --push . --file alpine/3.12/7.3/Dockerfile --tag zyuzka/php:73 --platform linux/amd64,linux/arm64