name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ORGA: 'zyuzka'
    strategy:
      matrix:
        image: [""]
        tag: [""]
        include:
          - image: 'alpine/3.12/7.3/Dockerfile'
            tag: "$ORGA/php:latest"

          - image: 'alpine/3.12/7.3/Dockerfile'
            tag: "$ORGA/php:7.3"
#            tag: ["$ORGA/php:latest", "$ORGA/php:7.3", "$ORGA/php:7.4-alpine3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker buildx build --push . --file ${{ matrix.image }} --tag ${{ matrix.tag }} --platform linux/amd64,linux/arm64
