name: Docker Image Master Release

on:
  push:
    branches: [ master ]

jobs:
  create-tag-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_AUTH_TOKEN }}

      - uses: actions/checkout@v2
        with:
          repository: 'zyuzka/tag-builder'
          path: 'tag-builder'
          token: ${{ secrets.GIT_AUTH_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - run: composer install --working-dir=./tag-builder/

      - name: Set ORGANISATION env variable
        run: echo "ORGANISATION=$(echo ${GITHUB_REPOSITORY_OWNER})" >> $GITHUB_ENV

      - id: set-matrix
        run: echo "::set-output name=matrix::$(php ./tag-builder/index.php -a build -c ./config.yml)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  build:
    needs: create-tag-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.create-tag-matrix.outputs.matrix) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.file }}
          tags: ${{ join(matrix.tags) }}
          platforms: linux/amd64,linux/arm64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
